name: Pret To Go
favicon: null
layout_spectrum: 0.6201584583614022
typography_spectrum: 0.5366242318414152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.44893442722968757
  lightness: 0.33450010558590293
  saturation: 0.940619939705357
  rhythmicContrast: 0.34067637426778674
purpose: []
